<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>{{ $resume->full_name ?: 'Resume' }}</title>
<style>
@page{margin:38px 46px 42px}*{box-sizing:border-box}body{margin:0;color:#292929;font-family:DejaVu Sans,sans-serif;font-size:10px;line-height:1.55}.header,.row,.skills,.section-heading{width:100%;border-collapse:collapse}.header{margin-bottom:25px}.identity{vertical-align:top;padding-right:22px}.photo-cell{width:112px;height:112px;vertical-align:top}.photo{display:block;width:112px;height:112px;object-fit:cover}.name{margin:0 0 5px;font-size:29px;line-height:1.12}.job-title{margin:0 0 10px;color:#ad8527;font-size:13px;font-weight:bold}.contact{color:#555;font-size:9px;line-height:1.75}.sep{color:#ad8527;padding:0 5px}.section{margin:0 0 18px}.section-title{margin:0 0 10px;padding-bottom:5px;border-bottom:1.5px solid #ad8527;color:#98731f;font-size:12px;letter-spacing:.8px;text-transform:uppercase;page-break-after:avoid}.section-heading{margin:0 0 10px;border-bottom:1.5px solid #ad8527;color:#98731f;page-break-after:avoid}.section-heading td{padding:0 0 5px;font-size:12px;font-weight:bold;letter-spacing:.8px;text-transform:uppercase}.section-heading .total{text-align:right;white-space:nowrap}.summary,.description{margin:0;color:#444}.entry{margin-bottom:12px;page-break-inside:avoid}.entry-title{font-size:10.5px;font-weight:bold;vertical-align:top}.date{color:#777;font-size:9px;text-align:right;vertical-align:top;white-space:nowrap}.subtitle{margin-top:1px;color:#98731f;font-weight:bold}.description{margin-top:4px;white-space:pre-line}.skill-category{width:29%;padding:0 14px 6px 0;color:#98731f;font-weight:bold;vertical-align:top}.skill-list{padding-bottom:6px;vertical-align:top}.extra{margin-bottom:10px;page-break-inside:avoid}.extra-title{color:#98731f;font-weight:bold}.muted{color:#777;font-size:9px}
.section-heading .total{font-size:12px;line-height:1.55}
</style></head><body>
@php
$contacts=array_values(array_filter([$email,$phone,$location,$linkedin,$github,$portfolio],fn($v)=>filled($v)));
$dateRange=fn($e)=>trim(($e['start_date']??$e['start_year']??'').((!empty($e['start_date'])||!empty($e['start_year'])||!empty($e['end_date'])||!empty($e['end_year']))?' - ':'').($e['end_date']??$e['end_year']??((!empty($e['start_date'])||!empty($e['start_year']))?'Present':'')));
@endphp
<table class="header"><tr><td class="identity"><h1 class="name">{{ $resume->full_name ?: $user->name }}</h1>@if($resume->professional_title)<p class="job-title">{{ $resume->professional_title }}</p>@endif @if($contacts)<div class="contact">@foreach($contacts as $contact)<span>{{ $contact }}</span>@if(!$loop->last)<span class="sep">|</span>@endif @endforeach</div>@endif</td>@if($includeProfilePhoto&&$avatar)<td class="photo-cell"><img class="photo" src="{{ $avatar }}" alt="Profile photo"></td>@endif</tr></table>
@if($resume->summary)<section class="section"><h2 class="section-title">Summary</h2><p class="summary">{{ $resume->summary }}</p></section>@endif
@if(count($experience))<section class="section"><table class="section-heading"><tr><td>Professional Experience</td><td class="total">Total Experience: {{ $totalExperience }} {{ (float)$totalExperience===1.0?'Year':'Years' }}</td></tr></table>@foreach($experience as $e)<div class="entry"><table class="row"><tr><td class="entry-title">{{ $e['job_title']??$e['title']??$e['position']??'' }}</td><td class="date">{{ $dateRange($e) }}</td></tr></table>@if(!empty($e['company']))<div class="subtitle">{{ $e['company'] }}</div>@endif @if(!empty($e['description']))<p class="description">{{ $e['description'] }}</p>@endif</div>@endforeach</section>@endif
@if(count($education))<section class="section"><h2 class="section-title">Education</h2>@foreach($education as $e) @php($field=$e['field_of_study']??$e['field']??'') <div class="entry"><table class="row"><tr><td class="entry-title">{{ $e['degree']??'' }}{{ !empty($e['degree'])&&$field?' in ':'' }}{{ $field }}</td><td class="date">{{ $dateRange($e) }}</td></tr></table><div class="subtitle">{{ $e['university']??$e['institution']??'' }}</div>@if(!empty($e['description']))<p class="description">{{ $e['description'] }}</p>@endif @if($gpa)<div class="muted">GPA: {{ $gpa }}</div>@endif</div>@endforeach</section>@endif
@if(count($skillGroups))<section class="section"><h2 class="section-title">Technical Skills</h2><table class="skills">@foreach($skillGroups as $category=>$items)<tr><td class="skill-category">{{ $category }}</td><td class="skill-list">{{ implode(', ',$items) }}</td></tr>@endforeach</table></section>@endif
@if(count($projects))<section class="section"><h2 class="section-title">Projects</h2>@foreach($projects as $p)<div class="entry"><div class="entry-title">{{ $p['name']??$p['title']??'' }}</div>@if(!empty($p['technologies']))<div class="subtitle">{{ is_array($p['technologies'])?implode(', ',$p['technologies']):$p['technologies'] }}</div>@endif @if(!empty($p['description']))<p class="description">{{ $p['description'] }}</p>@endif @if(!empty($p['url'])||!empty($p['link']))<div class="muted">{{ $p['url']??$p['link'] }}</div>@endif</div>@endforeach</section>@endif
@if(count($languages)||count($certificates)||count($activities)||count($achievements))<section class="section"><h2 class="section-title">Additional Information</h2>
@if(count($languages))<div class="extra"><div class="extra-title">Languages</div>@foreach($languages as $x)<div>{{ is_array($x)?($x['language']??$x['name']??''):$x }}@if(is_array($x)&&(!empty($x['proficiency'])||!empty($x['level'])))<span class="muted"> - {{ $x['proficiency']??$x['level'] }}</span>@endif</div>@endforeach</div>@endif
@if(count($certificates))<div class="extra"><div class="extra-title">Certifications</div>@foreach($certificates as $x)<div>{{ is_array($x)?($x['name']??$x['title']??''):$x }}@if(is_array($x)&&(!empty($x['issuer'])||!empty($x['year'])))<span class="muted"> - {{ $x['issuer']??'' }}{{ !empty($x['issuer'])&&!empty($x['year'])?', ':'' }}{{ $x['year']??'' }}</span>@endif</div>@endforeach</div>@endif
@foreach(['Activities'=>$activities,'Achievements'=>$achievements] as $label=>$items)@if(count($items))<div class="extra"><div class="extra-title">{{ $label }}</div>@foreach($items as $x)<div>@if(is_array($x))<strong>{{ $x['name']??$x['title']??'' }}</strong>@if(!empty($x['description'])) - {{ $x['description'] }}@endif @else{{ $x }}@endif</div>@endforeach</div>@endif @endforeach
</section>@endif
</body></html>
